# Generated by Django 5.2.1 on 2025-07-12 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_unique_together_review_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='feedback',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
